import { SampleDiffPreset } from "@/types";

export const SAMPLE_PRESETS: SampleDiffPreset[] = [
  {
    id: "fullstack-stripe",
    name: "Full-Stack: Stripe Billing & Subscriptions",
    description: "Multi-layer feature with UI modal, API route, DB migration, tests, and lockfile",
    template: "standard",
    tone: "technical",
    suggestedTitle: "feat(billing): add Stripe checkout session and subscription upgrade modal",
    commits: [
      "9f2b81a feat(billing): add Stripe checkout session handler and webhook stub",
      "4c1a70e feat(ui): add subscription upgrade modal with tier selection",
      "a88d321 db(migration): add stripeCustomerId and subscriptionStatus to User",
      "d44b209 test: add unit tests for billing checkout payload validation",
      "21c09ee chore(deps): install @stripe/stripe-js and stripe sdk",
    ].join("\n"),
    diff: [
      "diff --git a/package.json b/package.json",
      "index 38b9192..908fa11 100644",
      "--- a/package.json",
      "+++ b/package.json",
      "@@ -14,6 +14,8 @@",
      '     "@radix-ui/react-dialog": "^1.1.2",',
      '+    "@stripe/stripe-js": "^4.5.0",',
      '+    "stripe": "^16.12.0",',
      '     "clsx": "^2.1.1",',
      '     "lucide-react": "^0.468.0"',
      "   }",
      " }",
      "diff --git a/package-lock.json b/package-lock.json",
      "index e1024bc..898a31f 100644",
      "--- a/package-lock.json",
      "+++ b/package-lock.json",
      "@@ -820,6 +820,38 @@",
      '+    "node_modules/@stripe/stripe-js": {',
      '+      "version": "4.5.0",',
      '+      "resolved": "https://registry.npmjs.org/@stripe/stripe-js/-/stripe-js-4.5.0.tgz",',
      '+      "integrity": "sha512-lockfileMockDataOmitted..."',
      "+    },",
      '+    "node_modules/stripe": {',
      '+      "version": "16.12.0",',
      '+      "resolved": "https://registry.npmjs.org/stripe/-/stripe-16.12.0.tgz",',
      '+      "integrity": "sha512-lockfileMockDataOmitted..."',
      "+    }",
      "diff --git a/prisma/migrations/20260926_add_stripe_customer/migration.sql b/prisma/migrations/20260926_add_stripe_customer/migration.sql",
      "new file mode 100644",
      "index 0000000..748ac12",
      "--- /dev/null",
      "+++ b/prisma/migrations/20260926_add_stripe_customer/migration.sql",
      "@@ -0,0 +1,15 @@",
      '+-- AlterTable User',
      '+ALTER TABLE "User" ADD COLUMN "stripeCustomerId" TEXT;',
      '+ALTER TABLE "User" ADD COLUMN "subscriptionStatus" TEXT NOT NULL DEFAULT \'free\';',
      '+ALTER TABLE "User" ADD COLUMN "subscriptionTier" TEXT NOT NULL DEFAULT \'starter\';',
      '+ALTER TABLE "User" ADD COLUMN "currentPeriodEnd" TIMESTAMP(3);',
      "+",
      '+-- CreateIndex',
      '+CREATE UNIQUE INDEX "User_stripeCustomerId_key" ON "User"("stripeCustomerId");',
      '+CREATE INDEX "User_subscriptionStatus_idx" ON "User"("subscriptionStatus");',
      "diff --git a/src/app/api/stripe/checkout/route.ts b/src/app/api/stripe/checkout/route.ts",
      "new file mode 100644",
      "index 0000000..8d21b44",
      "--- /dev/null",
      "+++ b/src/app/api/stripe/checkout/route.ts",
      "@@ -0,0 +1,48 @@",
      '+import { NextResponse } from "next/server";',
      '+import Stripe from "stripe";',
      '+import { getCurrentUser } from "@/lib/auth";',
      '+import { db } from "@/lib/db";',
      "+",
      "+const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {",
      '+  apiVersion: "2024-06-20",',
      "+});",
      "+",
      "+export async function POST(req: Request) {",
      "+  try {",
      "+    const user = await getCurrentUser();",
      "+    if (!user) {",
      '+      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });',
      "+    }",
      "+",
      "+    const { priceId, successUrl, cancelUrl } = await req.json();",
      "+    if (!priceId) {",
      '+      return NextResponse.json({ error: "Missing priceId" }, { status: 400 });',
      "+    }",
      "+",
      "+    const session = await stripe.checkout.sessions.create({",
      "+      customer: user.stripeCustomerId ?? undefined,",
      "+      customer_email: user.stripeCustomerId ? undefined : user.email,",
      '+      payment_method_types: ["card"],',
      '+      line_items: [{ price: priceId, quantity: 1 }],',
      '+      mode: "subscription",',
      "+      success_url: successUrl || `${process.env.NEXTAUTH_URL}/dashboard?billing=success`,",
      "+      cancel_url: cancelUrl || `${process.env.NEXTAUTH_URL}/pricing`,",
      "+      metadata: { userId: user.id },",
      "+    });",
      "+",
      "+    return NextResponse.json({ url: session.url });",
      "+  } catch (error: any) {",
      '+    console.error("[STRIPE_CHECKOUT_ERROR]", error);',
      '+    return NextResponse.json({ error: error.message || "Internal error" }, { status: 500 });',
      "+  }",
      "+}",
      "diff --git a/src/components/billing/BillingModal.tsx b/src/components/billing/BillingModal.tsx",
      "new file mode 100644",
      "index 0000000..4b829ef",
      "--- /dev/null",
      "+++ b/src/components/billing/BillingModal.tsx",
      "@@ -0,0 +1,52 @@",
      '+"use client";',
      "+",
      '+import { useState } from "react";',
      '+import { Check, Loader2, Sparkles } from "lucide-react";',
      "+",
      "+interface BillingModalProps {",
      "+  isOpen: boolean;",
      "+  onClose: () => void;",
      "+  currentTier: string;",
      "+}",
      "+",
      "+export function BillingModal({ isOpen, onClose, currentTier }: BillingModalProps) {",
      "+  const [loading, setLoading] = useState(false);",
      "+",
      "+  if (!isOpen) return null;",
      "+",
      "+  const handleUpgrade = async (priceId: string) => {",
      "+    try {",
      "+      setLoading(true);",
      '+      const res = await fetch("/api/stripe/checkout", {',
      '+        method: "POST",',
      '+        headers: { "Content-Type": "application/json" },',
      "+        body: JSON.stringify({ priceId }),",
      "+      });",
      "+      const data = await res.json();",
      "+      if (data.url) {",
      "+        window.location.href = data.url;",
      "+      }",
      "+    } catch (err) {",
      "+      console.error(err);",
      "+    } finally {",
      "+      setLoading(false);",
      "+    }",
      "+  };",
      "+",
      "+  return (",
      '+    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">',
      '+      <div className="w-full max-w-lg rounded-xl border border-zinc-800 bg-zinc-900 p-6 shadow-2xl">',
      '+        <div className="flex items-center gap-2 text-indigo-400">',
      '+          <Sparkles className="h-5 w-5" />',
      '+          <h2 className="text-xl font-bold text-white">Upgrade Your Workspace</h2>',
      "+        </div>",
      '+        <p className="mt-2 text-sm text-zinc-400">',
      "+          Unlock unlimited pull request evaluations, team sharing, and custom AI templates.",
      "+        </p>",
      '+        <div className="mt-6 flex justify-end gap-3">',
      '+          <button onClick={onClose} className="px-4 py-2 text-sm text-zinc-400 hover:text-white">Cancel</button>',
      '+          <button onClick={() => handleUpgrade("price_pro_annual")} disabled={loading} className="rounded-lg bg-indigo-600 px-4 py-2 font-medium text-white hover:bg-indigo-500">',
      '+            {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : "Subscribe to Pro ($19/mo)"}',
      "+          </button>",
      "+        </div>",
      "+      </div>",
      "+    </div>",
      "+  );",
      "+}",
      "diff --git a/tests/billing.test.ts b/tests/billing.test.ts",
      "new file mode 100644",
      "index 0000000..f923c8a",
      "--- /dev/null",
      "+++ b/tests/billing.test.ts",
      "@@ -0,0 +1,32 @@",
      '+import { describe, it, expect, vi } from "vitest";',
      '+import { POST } from "@/app/api/stripe/checkout/route";',
      "+",
      '+describe("POST /api/stripe/checkout", () => {',
      '+  it("returns 401 when user is unauthenticated", async () => {',
      '+    const req = new Request("http://localhost:3000/api/stripe/checkout", {',
      '+      method: "POST",',
      '+      body: JSON.stringify({ priceId: "price_123" }),',
      "+    });",
      "+    const res = await POST(req);",
      "+    expect(res.status).toBe(401);",
      "+  });",
      "+",
      '+  it("rejects request without priceId", async () => {',
      '+    const req = new Request("http://localhost:3000/api/stripe/checkout", {',
      '+      method: "POST",',
      "+      body: JSON.stringify({}),",
      "+    });",
      "+    const res = await POST(req);",
      "+    expect(res.status).toBe(400);",
      "+  });",
      "+});",
    ].join("\n"),
  },
  {
    id: "bugfix-websocket-leak",
    name: "Bugfix: WebSocket Memory Leak on Reconnect",
    description: "Fixes event listener retention and stale ping timer leaks during connection dropouts",
    template: "bugfix",
    tone: "technical",
    suggestedTitle: "fix(ws): prevent event listener and timer leaks during rapid socket reconnection",
    commits: [
      "3a1290f fix(ws): clean up heartbeat timer and listener references on close",
      "8c7e421 fix(client): debounce reconnect loop to avoid cascading flood",
      "49021da test(ws): add stress test verifying zero listener buildup across 100 reconnects",
    ].join("\n"),
    diff: [
      "diff --git a/src/server/websocket-pool.ts b/src/server/websocket-pool.ts",
      "index b82a104..38f192b 100644",
      "--- a/src/server/websocket-pool.ts",
      "+++ b/src/server/websocket-pool.ts",
      "@@ -42,12 +42,24 @@ export class WebSocketPool {",
      "   public register(client: WebSocketClient): void {",
      "     this.clients.set(client.id, client);",
      "+    const pingTimer = setInterval(() => {",
      "+      if (client.readyState === WebSocket.OPEN) {",
      "+        client.ping();",
      "+      }",
      "+    }, 30000);",
      "+",
      "+    this.cleanupMap.set(client.id, () => {",
      "+      clearInterval(pingTimer);",
      "+      client.removeAllListeners();",
      "+    });",
      "   }",
      " ",
      "   public remove(clientId: string): void {",
      "     const client = this.clients.get(clientId);",
      "     if (client) {",
      "-      this.clients.delete(clientId);",
      "+      const cleanup = this.cleanupMap.get(clientId);",
      "+      if (cleanup) cleanup();",
      "+      this.cleanupMap.delete(clientId);",
      "+      this.clients.delete(clientId);",
      "     }",
      "   }",
      " }",
      "diff --git a/src/hooks/useRealtimeSocket.ts b/src/hooks/useRealtimeSocket.ts",
      "index c741fa2..941e309 100644",
      "--- a/src/hooks/useRealtimeSocket.ts",
      "+++ b/src/hooks/useRealtimeSocket.ts",
      "@@ -19,10 +19,18 @@ export function useRealtimeSocket(url: string) {",
      "   useEffect(() => {",
      "     let socket: WebSocket | null = new WebSocket(url);",
      "+    let reconnectTimeout: NodeJS.Timeout | null = null;",
      " ",
      "     const handleClose = () => {",
      "-      socket = new WebSocket(url);",
      "+      if (reconnectTimeout) clearTimeout(reconnectTimeout);",
      "+      reconnectTimeout = setTimeout(() => {",
      "+        socket = new WebSocket(url);",
      "+      }, 2000);",
      "     };",
      " ",
      '     socket.addEventListener("close", handleClose);',
      "-    return () => socket?.close();",
      "+    return () => {",
      "+      if (reconnectTimeout) clearTimeout(reconnectTimeout);",
      '+      socket?.removeEventListener("close", handleClose);',
      "+      socket?.close();",
      "+    };",
      "   }, [url]);",
      " }",
      "diff --git a/tests/websocket-reconnect.spec.ts b/tests/websocket-reconnect.spec.ts",
      "new file mode 100644",
      "index 0000000..93c1042",
      "--- /dev/null",
      "+++ b/tests/websocket-reconnect.spec.ts",
      "@@ -0,0 +1,38 @@",
      '+import { describe, it, expect } from "vitest";',
      '+import { WebSocketPool } from "@/server/websocket-pool";',
      "+",
      '+describe("WebSocketPool Leak Prevention", () => {',
      '+  it("cleans up timers and event listeners after disconnect", () => {',
      "+    const pool = new WebSocketPool();",
      "+    const mockClient = {",
      '+      id: "client-1",',
      "+      readyState: 1,",
      "+      ping: vi.fn(),",
      "+      removeAllListeners: vi.fn(),",
      "+    };",
      "+",
      "+    pool.register(mockClient as any);",
      "+    expect(pool.clients.size).toBe(1);",
      "+",
      '+    pool.remove("client-1");',
      "+    expect(pool.clients.size).toBe(0);",
      "+    expect(mockClient.removeAllListeners).toHaveBeenCalledOnce();",
      "+  });",
      "+});",
    ].join("\n"),
  },
  {
    id: "db-rbac-audit",
    name: "Enterprise DB & Security: RBAC Roles & Audit Logging",
    description: "Database schema migration, role-based access control middleware, and audit logs",
    template: "standard",
    tone: "detailed",
    suggestedTitle: "feat(security): implement RBAC permission middleware and immutable audit logging",
    commits: [
      "5e1829a feat(security): introduce RBAC role verification middleware for admin routes",
      "77a102c feat(audit): add structured immutable audit logger for mutation events",
      "128e401 db(schema): create Role, Permission, and AuditLog tables with indexes",
      "892c943 refactor(admin): protect sensitive tenant update endpoints with requireRole('ADMIN')",
    ].join("\n"),
    diff: [
      "diff --git a/prisma/schema.prisma b/prisma/schema.prisma",
      "index 421098b..1948201 100644",
      "--- a/prisma/schema.prisma",
      "+++ b/prisma/schema.prisma",
      "@@ -28,6 +28,19 @@ model User {",
      "   email     String   @unique",
      "   createdAt DateTime @default(now())",
      "+  roleId    String?",
      "+  role      Role?    @relation(fields: [roleId], references: [id])",
      "+  auditLogs AuditLog[]",
      "+}",
      "+",
      "+model Role {",
      "+  id          String   @id @default(cuid())",
      "+  name        String   @unique",
      "+  permissions String[]",
      "+  users       User[]",
      "+}",
      "+",
      "+model AuditLog {",
      "+  id        String   @id @default(cuid())",
      "+  actorId   String",
      "+  actor     User     @relation(fields: [actorId], references: [id])",
      "+  action    String",
      "+  target    String",
      "+  metadata  Json?",
      "+  createdAt DateTime @default(now())",
      "+",
      "+  @@index([actorId, createdAt])",
      "+}",
      "diff --git a/migrations/20260926_rbac_roles.sql b/migrations/20260926_rbac_roles.sql",
      "new file mode 100644",
      "index 0000000..99824c1",
      "--- /dev/null",
      "+++ b/migrations/20260926_rbac_roles.sql",
      "@@ -0,0 +1,28 @@",
      '+CREATE TABLE "Role" (',
      '+    "id" TEXT NOT NULL,',
      '+    "name" TEXT NOT NULL,',
      '+    "permissions" TEXT[],',
      '+    CONSTRAINT "Role_pkey" PRIMARY KEY ("id")',
      "+);",
      "+",
      '+CREATE TABLE "AuditLog" (',
      '+    "id" TEXT NOT NULL,',
      '+    "actorId" TEXT NOT NULL,',
      '+    "action" TEXT NOT NULL,',
      '+    "target" TEXT NOT NULL,',
      '+    "metadata" JSONB,',
      '+    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,',
      '+    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")',
      "+);",
      "+",
      '+ALTER TABLE "User" ADD COLUMN "roleId" TEXT;',
      '+CREATE INDEX "AuditLog_actorId_createdAt_idx" ON "AuditLog"("actorId", "createdAt");',
      "diff --git a/src/middleware/rbac.ts b/src/middleware/rbac.ts",
      "new file mode 100644",
      "index 0000000..348ef19",
      "--- /dev/null",
      "+++ b/src/middleware/rbac.ts",
      "@@ -0,0 +1,38 @@",
      '+import { NextRequest, NextResponse } from "next/server";',
      '+import { getCurrentUser } from "@/lib/auth";',
      "+",
      "+export function requireRole(allowedRoles: string[]) {",
      "+  return async (req: NextRequest) => {",
      "+    const user = await getCurrentUser();",
      "+    if (!user) {",
      '+      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });',
      "+    }",
      "+",
      "+    if (!user.role || !allowedRoles.includes(user.role.name)) {",
      "+      return NextResponse.json(",
      '+        { error: "Forbidden: insufficient role privileges" },',
      "+        { status: 403 }",
      "+      );",
      "+    }",
      "+",
      "+    return null;",
      "+  };",
      "+}",
      "diff --git a/src/lib/audit-logger.ts b/src/lib/audit-logger.ts",
      "new file mode 100644",
      "index 0000000..892e011",
      "--- /dev/null",
      "+++ b/src/lib/audit-logger.ts",
      "@@ -0,0 +1,24 @@",
      '+import { db } from "@/lib/db";',
      "+",
      "+export interface AuditPayload {",
      "+  actorId: string;",
      "+  action: string;",
      "+  target: string;",
      "+  metadata?: Record<string, unknown>;",
      "+}",
      "+",
      "+export async function logAuditEvent(payload: AuditPayload): Promise<void> {",
      "+  try {",
      "+    await db.auditLog.create({",
      "+      data: {",
      "+        actorId: payload.actorId,",
      "+        action: payload.action,",
      "+        target: payload.target,",
      "+        metadata: payload.metadata as any,",
      "+      },",
      "+    });",
      "+  } catch (err) {",
      '+    console.error("[AUDIT_LOG_FAILURE]", err);',
      "+  }",
      "+}",
    ].join("\n"),
  },
];
